ACME External Account Binding (EAB) implementation
nabsul/kcert pull request #100
Opened 2023-10-23 09:02 UTC by Zegorax

This PR introduces the following features / fixes :
- External Account Binding
- Namespace-contrained mode. It allows to specify which namespaces to check. It will prevent to have cluster-wide requests when not allowed to do so (Rancher clusters for example)
- Allow anonymous SMTP connection
- Updated Helm chart to better reflect namespacing mode and other changes.
- Helm chart no longers creates the secret for the SMTP password. Instead, it's better to create a secret on the cluster and specify the secret name and key to fetch the value (prevent storing raw values in the value files)

2023-10-23 09:14 UTC, Zegorax commented
Please test it extensively :)

2023-10-25 13:23 UTC, nabsul commented
Thanks @Zegorax ! I'll try to work through your PRs ASAP, but realistically it might not be until next week.

2023-10-26 08:33 UTC, Zegorax commented
To test EAB for free, ZeroSSL could be used. It offers a free tier and only use EAB authentication.

2023-10-29 20:22 UTC, nabsul commented
@Zegorax Does the README need to be updated for the secrets instructions?

2023-10-29 20:24 UTC, Zegorax commented
You're right, I forgot to update it. Do you want to update it yourself or do I push a new commit?

2023-10-29 20:33 UTC, nabsul commented
> You're right, I forgot to update it. Do you want to update it yourself or do I push a new commit?

Please go ahead and update accordingly, I'm still reviewing the PR.

2023-10-29 21:04 UTC, Zegorax commented
> Please go ahead and update accordingly, I'm still reviewing the PR.

Done

2023-10-30 13:58 UTC, nabsul requested changes
Not completely done with feedback, but here's a batch :-)

2023-10-30 13:58 UTC, nabsul commented on Services/AcmeClient.cs
> +        // Small retry wrapper in case of HTTP failure
Is a retry needed here? I would hold off on adding retries unless there's good reason to have it.

2023-10-30 13:58 UTC, nabsul commented on Services/K8sClient.cs
> +
nit: delete new line

2023-10-30 13:58 UTC, nabsul commented on Services/K8sWatchClient.cs
> +}
nit: new line

2023-10-30 13:58 UTC, nabsul commented on Services/KCertClient.cs
> +}
nit: new line

2023-10-30 13:58 UTC, nabsul commented on Services/KCertConfig.cs
> +}
newline

2023-10-30 13:58 UTC, nabsul commented on Services/KCertConfig.cs
> +    public bool NamespaceConstraints => GetBool("KCert:NamespaceConstraints");
Instead of two config parameters, how about defaulting the list to null to indicate all namespaces?

2023-10-30 13:58 UTC, nabsul commented on Services/RenewalHandler.cs
> +}
new line

2023-10-30 13:58 UTC, nabsul commented on charts/kcert/templates/040-ClusterRoleBinding.yaml
> +{{ end }}
new line

2023-10-31 00:29 UTC, nabsul commented on charts/kcert/values.yaml
> +  deployment: kcert
I think this `names` section went away and was replaced by `kcert.fullname` for simplicity.  Are these values used anywhere?

2023-10-31 00:29 UTC, nabsul commented on charts/kcert/values.yaml
> +securityContext: []
Is this used anywhere?

2023-10-31 00:31 UTC, nabsul commented on charts/kcert/values.yaml
> +  port: 25
I feel like null is more appropriate, since I'm not sure if 25 is a reasonable default port number (it's the unsecure SMTP port, which is probably not recommended in most cases)

2023-10-31 00:35 UTC, nabsul commented on charts/kcert/templates/070-Deployment.yaml
> +        securityContext:
will the default of `{}` encode correctly here?

2023-10-31 00:37 UTC, nabsul commented on charts/kcert/templates/050-Role.yaml
> +{{ if .Values.names.clusterRole }}
I guess if you delete the `names` section in `values.yaml`, this if conditional will have to change.

2023-10-31 00:37 UTC, nabsul commented on charts/kcert/templates/030-ClusterRole.yaml
> +{{ if .Values.names.clusterRole }}
similar comment about the names section. (see other comment in next file)

2023-10-31 00:43 UTC, nabsul commented on README.md
I know the instructions for setting up SMTP are very basic, but I think they need to be updated since we now expect the user to create the kubernetes secret manually.

2023-10-31 14:41 UTC, nabsul commented on Services/K8sClient.cs
> +                    .Aggregate(async (current, next) =>
This looks like it wouldn't work as expected... Creating a new V1IngressList and merging all the results into it. I don't think the continuation token will be valid in this case.

2023-10-31 14:45 UTC, nabsul commented on Services/K8sClient.cs
>      public async IAsyncEnumerable<V1Ingress> GetAllIngressesAsync()
How about refactoring it this way: https://github.com/nabsul/kcert/pull/103/files

I'm also seeing that in some places we're ignoring the continuation token. The above change with the helper function will make it easier to refactor all List calls to use the continuation token...

2023-11-07 22:58 UTC, nabsul commented on README.md
> +### Namespace-constraigned installations
I feel like I've seen the spelling of `constraigned ` like this before, but `constrained` seems to be more common... or maybe just American :-D

2023-11-10 08:08 UTC, Zegorax commented on README.md
> +### Namespace-constraigned installations
It's a typo!

2023-11-10 08:12 UTC, Zegorax commented on Services/K8sClient.cs
>      public async IAsyncEnumerable<V1Ingress> GetAllIngressesAsync()
Done

2023-11-11 03:56 UTC, nabsul commented on Services/AcmeClient.cs
> +        int maxRetries = _cfg.EnableHttpRetry ? 3 : 0;
I still think this isn't needed. I haven't had any reports of flakiness on these APIs or the need for something like this.

But also, I'm pretty sure I'm seeing a bug here. Won't `3` actually result in 4 tries? :-) 

Let's revert this back to the original. If you feel strongly about this, maybe we can bring in the Polly library to avoid taking responsibility for a retry algorithm...

2023-11-11 03:56 UTC, nabsul commented on Services/AcmeClient.cs
> +        int maxRetries = _cfg.EnableHttpRetry ? 3 : 0;
(I mean add retries in a separate PR)

2023-11-11 04:01 UTC, nabsul commented on Services/K8sClient.cs
> +        return await namespaces
I think this needs to be updated.

2023-11-11 04:04 UTC, nabsul commented on Services/KCertConfig.cs
> +    private bool? GetOptionalBool(string key) => _cfg.GetValue<bool?>(key);
You can use `_cfg.GetValue<bool>(lkey, false)` here

2023-11-11 04:06 UTC, nabsul commented on charts/kcert/values.yaml
> +acmeEmail: asdfs
I think this needs to stay as null so that it errors out if not set.

2023-11-11 04:08 UTC, nabsul commented on charts/kcert/values.yaml
> +  secretName: kcert-prd-hmac-secret
Should this default be null?

2023-11-11 04:13 UTC, nabsul commented on charts/kcert/templates/050-Role.yaml
> +- apiGroups: [""]
To support specific namespaces, don't we need to provide a list of them here somewhere?

2023-11-11 04:14 UTC, nabsul requested changes
I think we're almost there! 

By the way, have you tested this code yet?

2023-11-11 04:39 UTC, nabsul commented on Services/AcmeClient.cs
> +        int maxRetries = _cfg.EnableHttpRetry ? 3 : 0;
If I were to improve upon this retry logic:

```c#
        // Small retry wrapper in case of HTTP failure.
        int tries = _cfg.EnableHttpRetry ? 3 : 1;
        while (tries-- > 0)
        {
            try
            {
                return await _http.PostAsync(uri, content);
            }
            catch (Exception e)
            {
                if (tries == 0) throw;
                _log.LogError(e, "HTTP request failed. Retrying in 3 seconds.");
            }

            await Task.Delay(TimeSpan.FromSeconds(3));
        }

        throw new Exception("This line should be unreachable.");
```

2024-02-16 21:05 UTC, closed without merging

2024-02-16 21:05 UTC, nabsul commented
Merged after cloning and editing this branch.