Ptik31/await ingress propagation
nabsul/kcert pull request #57
Opened 2022-07-12 14:12 UTC by ptik31

2022-07-12 15:21 UTC, nabsul commented
Very cool, thanks! I'll try to get this reviewed and merged as soon as I have some time.

2022-08-07 15:52 UTC, nabsul commented
Hi, I know it's been quite a while, but I life is extra busy at the moment :-). 

But I haven't forgotten about this! I believe things will start to free up for me in about 2 weeks. Then, I need to wrap up the PRs that I already have on this project, and this PR will be next. Thank you for your patience, and I really do appreciate the contribution!

2022-09-08 05:29 UTC, ptik31 commented
Hi, thank you for keeping me up to date.
Please don't worry about us, we temporarely switched to our own docker image built from your awesome dockerfile :)

All the best

2022-11-17 07:21 UTC, ptik31 commented
Hi @nabsul , [thats](https://github.com/nabsul/kcert/issues/55#issuecomment-1253040199) a really great idea. I was investigating it and found these possible approaches:

After successful setting up the newly created ingress, the controller adds the following properties to the ressource manifest:
- manager
- load-balancer.ingress.ip

![image](https://user-images.githubusercontent.com/102354084/202184436-233edb6a-9092-493a-8d0d-30637d0f6d42.png)

I'll inform you after my changes are done to review them again.

Please let me know if you suggest further exploring.

2022-11-17 07:24 UTC, ptik31 commented
Hi @nabsul , I've implemented the loadbalancer approach. You can review now..
Let me know about other findings or ideas.

2022-11-21 14:28 UTC, nabsul requested changes

2022-11-21 14:28 UTC, nabsul commented on Services/KCertConfig.cs
> +    public int MaxPropagationWaitTimeSeconds => GetInt("ChallengeIngress:MaxPropagationWaitTimeSeconds");
For consistency, I would prefer that these two parameters be TimeSpans, like `AcmeWaitTime`. So:

- Keep the names in `appsettings.json` as they are
- Parse the value to a TimeSpan type
- Drop "Seconds" and "Milliseconds" from the member name since it's a timespan now.

2022-11-21 14:31 UTC, nabsul commented
Wow! Thanks for this contribution @ptik31. I looked over the change, and it's all clean and concise. And thank you for the code quality improvements as well (unused using, wrong LogError, etc.).

The change looks completely reasonable. I will just need to find time to carefully review the new function and test it. Hopefully this week or weekend, but it could take a few weeks if things get too busy.

2022-11-21 14:40 UTC, nabsul commented on appsettings.json
> +    "MaxPropagationWaitTimeSeconds": 300,
I'd like to think a little more about these default values. 

- Is an interval of 1s too fast? Are we hitting the K8s API too much? Probably this is an OK value, but maybe 5 seconds would also be fast enough?
- Is 5 minutes for a wait time too long? Should nginx ever take more than a minute? Would it be better to fail sooner, so tha you're not left waiting too long for an error message to occur? (it'll also mean you'll have to look through a wider range of logs)

2022-11-22 12:53 UTC, ptik31 commented on appsettings.json
> +    "MaxPropagationWaitTimeSeconds": 300,
Hi @nabsul, my benchmark has shown that it took up to three minutes (maximum) in our cluster. That's why I then just rounded up to 5 Minutes. I changed it to 1 minute.

Regarding to the 1s check interval: My Idea was not to lose time if the ingress would be ready inbetween of the first 1s.
I changed it to 5s

I'm happy with your default proposals, because everyone who's going to use kcert is allowed to adjust the values, if needed :)

Thank you for your advices.

You can go ahead reviewing the PR.

2022-11-22 12:54 UTC, ptik31 commented on Services/KCertConfig.cs
> +    public int MaxPropagationWaitTimeSeconds => GetInt("ChallengeIngress:MaxPropagationWaitTimeSeconds");
done

2022-11-22 13:19 UTC, nabsul commented on appsettings.json
> +    "MaxPropagationWaitTimeSeconds": 300,
If you're seeing 3 minutes of delay, then yes I agree with 5 minutes total time. Let's go with that. But let's keep the 5s just to reduce the number of times we keep hitting the K8s API.

2022-11-22 13:21 UTC, ptik31 commented on appsettings.json
> +    "MaxPropagationWaitTimeSeconds": 300,
done

2022-11-23 02:13 UTC, nabsul requested changes
I believe this is my last set of change requests :-)

2022-11-23 02:13 UTC, nabsul commented on Services/KCertClient.cs
> +                var isIngressPropagated = ingress.Status.LoadBalancer.Ingress?.Any() ?? default;
nit: can we explicitly use `false` instead of `default`?

2022-11-23 05:13 UTC, ptik31 commented on Services/KCertClient.cs
> +            async Task<bool> IsIngressPropagated()
I'm not sure if I understood your change request well. Please give it another check pls :)
I moved out the IsIngressPropagated method (btw. I do think that it WAS using local variables -> ingressName and ingressNamespace)

2022-11-23 05:17 UTC, ptik31 commented on Services/KCertClient.cs
> +            _log.LogError(ex, "HTTP Operation failed with responses: {resp}", ex.Response.Content);
Ok, I don't know why I changed that at all. Maybe it was the Resharper :P
Oh, I see.. There was a missing 's' in "respon**_**es". But it should have been in singular from it's beginning. Changed it :)

2022-11-23 05:18 UTC, ptik31 commented on Services/KCertClient.cs
> +                var isIngressPropagated = ingress.Status.LoadBalancer.Ingress?.Any() ?? default;
Of course sir, done

2022-11-23 05:20 UTC, ptik31 commented
@nabsul, your turn. Pls take as many review turns as you need to approve :)

2022-11-24 00:10 UTC, nabsul approved these changes

2022-11-24 00:10 UTC, merged

2022-11-24 00:13 UTC, nabsul commented
Alrighty! I'll try to get everything tested and released in the next few days.

2022-11-24 05:33 UTC, ptik31 commented
Great, thank you for the great collaboration :)