fix: made ingressClass configurable
nabsul/kcert pull request #80
Opened 2022-12-30 09:32 UTC by dheeth

Everyone may not be having ingress class as default nginx, so made it configurable for those who want to create kcert-ingress with some other class of their own

2022-12-30 23:57 UTC, nabsul requested changes
Thank you for this contribution. I really like the idea, but I think this should be implemented slightly differently:

- Bring back the old version that included the annotation: https://github.com/nabsul/kcert/commit/af917297d8e58a2ba81c6131fe7d0ebde96b81ac
- Add a value called `ingressAnnotation` similar to `className`
- Wrap both the annotation section and the classname sections in a `{{ if }}` so that they are completely hidden if the value is null.
- Default `className` to `nginx` and `ingressAnnotation` to `null`

- Actually, I'd also propose renaming `className` to `ingressClassName` for more clarity

This will allow the user to switch between using either annotations or classnames (or even both). Classname should be the default behavior since that's the newer way things are being done.

If you'd like to make these changes, I'd be happy to wait for you to do that. But if not, not worries. This is a good suggestion and I'd be happy to write it myself in the next few weeks.

2023-01-02 08:00 UTC, dheeth commented
Done changes as requested, please verify once

2023-01-05 02:11 UTC, nabsul requested changes
Definitely on the right track! 

I made a few suggestions. I will try to find time to test the code this weekend.

Thanks!

2023-01-05 02:11 UTC, nabsul commented on charts/kcert-ingress/templates/001-Ingress.yaml
> +  {{- if and (.Values.ingressClassAnnotation) (.Values.ingressClassName) }}
Since you're using `required` on line 10, there's no need to check for `ingressClassName` in the if-statement.

2023-01-05 02:11 UTC, nabsul commented on charts/kcert-ingress/templates/001-Ingress.yaml
> +  {{- if and (not .Values.ingressClassAnnotation) (.Values.ingressClassName) }}
Similar to the above comment on the if-statement.

2023-01-05 02:11 UTC, nabsul commented on charts/kcert-ingress/templates/001-Ingress.yaml
> +  {{- else if and (not .Values.ingressClassAnnotation) (not .Values.ingressClassName) }}
I think there is no need for this else statement. If it is ever true, the `required` part will fail. So I think you can just remove it completely...

2023-01-08 07:50 UTC, dheeth commented
Will be doing it today, was busy with some other tasks

2023-02-09 16:36 UTC, dheeth commented on charts/kcert-ingress/templates/001-Ingress.yaml
> +  {{- if and (.Values.ingressClassAnnotation) (.Values.ingressClassName) }}
This is done intentionally as I am giving preference to annotation if both class name as well as annotation is set to true by the user

2023-02-09 16:42 UTC, dheeth commented on charts/kcert-ingress/templates/001-Ingress.yaml
> +  {{- if and (.Values.ingressClassAnnotation) (.Values.ingressClassName) }}
Done these changes

2023-02-09 16:42 UTC, dheeth commented on charts/kcert-ingress/templates/001-Ingress.yaml
> +  {{- if and (not .Values.ingressClassAnnotation) (.Values.ingressClassName) }}
Done

2023-02-09 16:42 UTC, dheeth commented
@nabsul Please check I have updated the changes as requested

2023-03-11 22:59 UTC, nabsul commented on charts/kcert-ingress/values.yaml
> +# If set to true, it'll ignore ingressClassName and use the same in ingress class annotation as using both in same ingress are not supported but ingressClassName is still required to use in annotatio
To clarify a little more, instead of:

> # If set to true, it'll ignore ingressClassName and use the same in ingress class annotation as using both in same ingress are not supported but ingressClassName is still required to use in annotation


how about:

> # If set to true, it'll use ingressClassName as an annotation instead of the more recent dedicated ingressClassName field.

2023-03-11 22:59 UTC, nabsul commented on charts/kcert-ingress/values.yaml
> +ingressClassAnnotation: false
I got a little confused thinking that to use annotation I would set this value to "nginx". To make it clearer that it's a boolean, let's rename it to `useIngressClassAnnotation`

2023-03-11 23:13 UTC, nabsul commented
I'll go ahead and take care of those last little tweaks on my own. Thanks for the contribution!

2023-03-11 23:19 UTC, nabsul commented
merged in #93

2023-03-11 23:19 UTC, closed without merging